---
# zsh role defaults
oh_my_zsh_repo: https://github.com/ohmyzsh/ohmyzsh.git

zsh_plugins:
  - name: zsh-autosuggestions
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
  - name: zsh-syntax-highlighting
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
  - name: zsh-completions
    repo: https://github.com/zsh-users/zsh-completions.git
